### ISSUE TITLE
Inconsistencies in raw data

### ISSUE THREAD

**Issue by weka511** [mattreidy/Cholangiocarcinoma_ML#6]
I have found 3 inconsistencies in the all_raw_data.txt. In each case my script has identified two records with the same Id, but different opinions about the type of cancer.
Id|Cancer 1|Cancer2
----------------------------------|-------------------------------------------------|-------------------------------------------------
P-0000159P-0000159-T01-IM3|Intrahepatic Cholangiocarcinoma|Cholangio Extrahepatic
P-0009916P-0009916-T01-IM5|Extrahepatic Cholangiocarcinoma|IHCH
P-0011240P-0011240-T01-IM5|Cholangio Extrahepatic|IHCH

**Comment by mattreidy** [comment]
During deduplication I made P-0000159P-0000159-T01-IM3 cancer_type = "Intrahepatic Cholangiocarcinoma" since two of the three instances of the records were intrahepatic (Intrahepatic Cholangiocarcinoma and IHCH).

I made P-0009916P-0009916-T01-IM5 cancer_type = "Extrahepatic Cholangiocarcinoma" based on similar logic.

I made P-0011240P-0011240-T01-IM5 cancer type = "Cholangiocarcinoma" again, based on similar logic.
